# see https://github.com/nvbangg/ReVanced-APK-Builder/blob/main/CONFIG.md for more detailed explanations

[YouTube]
patches-source = "nvbangg/nvbangg-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "nvbangg"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"

[YouTube-ReVanced]
excluded-patches = "'Custom branding'"
app-name = "youtube"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"

[YouTube-Morphe]
patches-source = "MorpheApp/morphe-patches"
excluded-patches = "'Custom branding'"
cli-source = "MorpheApp/morphe-cli"
app-name = "youtube"
rv-brand = "morphe"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"

[YouTube-Music]
excluded-patches = "'Permanent repeat' 'Custom branding' 'Hide buttons' 'Hide category bar' 'Change miniplayer color' 'Theme' 'Enable debugging' 'Check watch history domain name resolution' 'Spoof video streams' 'Force original audio'"
rv-brand = "nvbangg"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"

[YouTube-Music-ReVanced]
excluded-patches = "'Custom branding'"
app-name = "youtube-music"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"

[YouTube-Music-Morphe]
patches-source = "MorpheApp/morphe-patches"
excluded-patches = "'Custom branding'"
cli-source = "MorpheApp/morphe-cli"
app-name = "youtube-music"
rv-brand = "morphe"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"

[Google-Photos]
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"

[Spotify]
patches-source = "anddea/revanced-patches"
rv-brand = "anddea"
uptodown-dlurl = "https://spotify.en.uptodown.com/android"

[TikTok]
uptodown-dlurl = "https://tiktok.en.uptodown.com/android"

[Instagram]
uptodown-dlurl = "https://instagram.en.uptodown.com/android"

[Duolingo]
uptodown-dlurl = "https://duolingo.en.uptodown.com/android"

[Facebook]
uptodown-dlurl = "https://facebook.en.uptodown.com/android"

[Messenger]
uptodown-dlurl = "https://facebook-messenger.en.uptodown.com/android"

[Telegram]
patches-source = "Aunali321/ReVancedExperiments"
app-name = "telegram-revanced-experiments"
rv-brand = "aunali321"
apkmirror-dlurl = "https://www.apkmirror.com/apk/telegram-fz-llc/telegram/"
uptodown-dlurl = "https://telegram.en.uptodown.com/android"

[Telegram-Web]
patches-source = "Aunali321/ReVancedExperiments"
app-name = "telegram-web-revanced-experiments"
rv-brand = "aunali321"
apkmirror-dlurl = "https://www.apkmirror.com/apk/telegram-fz-llc/telegram-web-version/"

[Twitter]
uptodown-dlurl = "https://twitter.en.uptodown.com/android"

[Twitter-Piko]
patches-source = "crimera/piko"
patches-version = "dev"
rv-brand = "crimera"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"

[Twitch]
uptodown-dlurl = "https://twitch.en.uptodown.com/android"

[Reddit]
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"

[Reddit-RVX-Morphed]
patches-source = "wchill/rvx-morphed"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "wchill"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"

[Reddit-Privacy-Patches]
patches-source = "jkennethcarino/privacy-revanced-patches"
rv-brand = "jkennethcarino"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"

[SoundCloud]
uptodown-dlurl = "https://soundcloud.en.uptodown.com/android"

[Viber]
apkmirror-dlurl = "https://www.apkmirror.com/apk/viber-media-s-a-r-l/viber/"

[Prime-Video]
uptodown-dlurl = "https://amazon-video.en.uptodown.com/android"

[Disney]
uptodown-dlurl = "https://disney-disneyplus.en.uptodown.com/android"

[Tumblr]
uptodown-dlurl = "https://tumblr.en.uptodown.com/android"

[Photomath]
uptodown-dlurl = "https://photomath.en.uptodown.com/android"

[Google-Recorder]
uptodown-dlurl = "https://opnemer.en.uptodown.com/android"

[Strava]
uptodown-dlurl = "https://strava.en.uptodown.com/android"

[MyFitnessPal]
uptodown-dlurl = "https://calorie-counter-myfitnesspal.en.uptodown.com/android"

[Crunchyroll]
uptodown-dlurl = "https://crunchyroll.en.uptodown.com/android"

[Peacock-TV]
uptodown-dlurl = "https://peacock-tv.en.uptodown.com/android"

[Cricbuzz]
uptodown-dlurl = "https://cricbuzz-cricket-scores-and-news.en.uptodown.com/android"

[RAR]
uptodown-dlurl = "https://rar-for-android.en.uptodown.com/android"

[AZ-Screen-Recorder]
patches-source = "scrazzz/revanced-patches-scruz"
patches-version = "dev"
rv-brand = "scrazzz"
uptodown-dlurl = "https://az-screen-recorder.en.uptodown.com/android"

[Nova-Launcher]
patches-source = "indrastorms/Dropped-Patches"
app-name = "nova-launcher-dropped"
rv-brand = "indrastorms"
uptodown-dlurl = "https://nova-launcher.en.uptodown.com/android"

[Proton-Mail]
uptodown-dlurl = "https://protonmail.en.uptodown.com/android"

[Proton-VPN]
uptodown-dlurl = "https://protonvpn.en.uptodown.com/android"

[Meme-Generator]
uptodown-dlurl = "https://meme-generator-free.en.uptodown.com/android"
